
services:
  database:
    image: postgres:15
    container_name: nestjs_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydb
    command: sh -c "npm install && npm run build && npm run start:dev"
    networks:
      - backend
    volumes:
      - .:/usr/src/app

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
