services:
  test-repository-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: repository-test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repository-test-db
    ports:
      - "5434:5432"